FROM python:3.9

WORKDIR /app

RUN pip3 install poetry

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

COPY . app/

COPY ../pyproject.toml app/
COPY ../README.md app/

RUN poetry shell
RUN poetry lock
RUN poetry install