FROM python:3.10

WORKDIR /asmac_backend

RUN pip3 install poetry

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

COPY . asmac_backend/
COPY . ./

RUN poetry config virtualenvs.create false
RUN poetry lock
RUN poetry install